### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#418]
## Road Map
- [x] Nova-style spells for close range combat
- [ ] Aura spells
- [x] Experimental Cardmason

Backburner Tasks:
- [ ] Balance builds https://github.com/jdoleary/Spellmasons/issues/1271
- [ ] Get livestream on Steam https://partner.steamgames.com/doc/store/broadcast
- [x] https://github.com/jdoleary/Spellmasons/issues/1273
- [ ] #1216
- [ ] New Content Milestone https://github.com/jdoleary/Spellmasons/milestone/18
- [ ] High Consideration Milestone https://github.com/jdoleary/Spellmasons/milestone/16
- [ ] #382 
- [ ] #231 Auras
- [ ] #814
- [ ] #533

**Comment by jdoleary** [comment]
This issue is outdated.  Many of these things have been implemented, some are no longer relevant
